"use client"

import { useEffect, useState } from "react"
import { useParams } from "next/navigation"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Calendar, FileText, Loader2, AlertCircle } from "lucide-react"
import Link from "next/link"

interface SharedScan {
  id: string
  symptoms: string[]
  date: string
  userName: string
  createdAt: string
}

export default function SharedScanPage() {
  const params = useParams()
  const [scan, setScan] = useState<SharedScan | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchSharedScan = async () => {
      try {
        const response = await fetch(`/api/scans/${params.id}`)
        const data = await response.json()

        if (data.success) {
          setScan(data.scan)
        } else {
          setError(data.error || "Scan not found")
        }
      } catch (err) {
        setError("Failed to load shared scan")
      } finally {
        setLoading(false)
      }
    }

    if (params.id) {
      fetchSharedScan()
    }
  }, [params.id])

  if (loading) {
    return (
      <div className="container max-w-2xl py-8 md:py-12">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="flex flex-col items-center gap-4">
            <Loader2 className="h-8 w-8 animate-spin" />
            <p>Loading shared scan...</p>
          </div>
        </div>
      </div>
    )
  }

  if (error || !scan) {
    return (
      <div className="container max-w-2xl py-8 md:py-12">
        <Card className="border-destructive">
          <CardContent className="p-8 text-center">
            <AlertCircle className="h-12 w-12 text-destructive mx-auto mb-4" />
            <h2 className="text-xl font-semibold mb-2">Scan Not Found</h2>
            <p className="text-muted-foreground mb-6">
              {error || "The shared scan you're looking for doesn't exist or has expired."}
            </p>
            <Button asChild>
              <Link href="/">Go to Home</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="container max-w-2xl py-8 md:py-12">
      <div className="space-y-4 mb-8">
        <h1 className="text-3xl font-bold tracking-tighter md:text-4xl text-center">Shared VitaScan Report</h1>
        <p className="text-muted-foreground md:text-xl text-center">
          Health symptom analysis shared by {scan.userName}
        </p>
      </div>

      <Card className="border-l-4 border-l-primary">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Symptom Analysis Report
          </CardTitle>
          <CardDescription className="flex items-center gap-2">
            <Calendar className="h-4 w-4" />
            {new Date(scan.date).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            })}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div>
            <h3 className="font-semibold mb-3">Reported Symptoms:</h3>
            <div className="flex flex-wrap gap-2">
              {scan.symptoms.map((symptom, index) => (
                <Badge key={index} variant="secondary" className="text-sm">
                  {symptom}
                </Badge>
              ))}
            </div>
          </div>

          <div className="bg-muted p-4 rounded-lg">
            <p className="text-sm text-muted-foreground">
              <strong>Disclaimer:</strong> This is a symptom report generated by VitaScan. This information is for
              reference only and should not be used as a substitute for professional medical advice, diagnosis, or
              treatment. Always consult with a qualified healthcare provider for medical concerns.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 pt-4">
            <Button asChild className="flex-1">
              <Link href="/symptom-checker">Try VitaScan</Link>
            </Button>
            <Button variant="outline" asChild className="flex-1 bg-transparent">
              <Link href="/">Learn More</Link>
            </Button>
          </div>
        </CardContent>
      </Card>

      <div className="mt-8 text-center">
        <p className="text-sm text-muted-foreground">
          Powered by <span className="font-semibold gradient-text">VitaScan</span> - AI-Powered Health Analysis
        </p>
      </div>
    </div>
  )
}
